services:
  postgres:
    container_name: postgres_template
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: template
  redis:
    container_name: redis_template
    image: redis
    restart: always
    ports:
      - 6379:6379
  activemq:
    image: apache/activemq-classic:5.18.6
    container_name: amq_template
    restart: unless-stopped
    ports:
      - 5672:5672 # AMQP protocol
      - 8161:8161 # management
    environment:
      ACTIVEMQ_CONNECTION_USER: admin
      ACTIVEMQ_CONNECTION_PASSWORD: admin
      ACTIVEMQ_WEB_USER: admin
      ACTIVEMQ_WEB_PASSWORD: admin
    volumes:
      - ./.amq/activemq.xml:/opt/apache-activemq/conf/activemq.xml # copy activemq.example.xml to activemq.xml
      - ./.amq/data:/opt/apache-activemq/data # make directory if the system does not create one
  rabbitmq:
      container_name: rmq_template
      image: rabbitmq:3-management
      hostname: rabbitmq-template
      environment:
        RABBITMQ_DEFAULT_USER: "admin"
        RABBITMQ_DEFAULT_PASS: "admin"
        RABBITMQ_ERLANG_COOKIE: "admin"
      ports:
        - 5673:5672 # AMQP protocol
        - 15672:15672 # Management UI
      volumes:
        - ".rmq:/var/lib/rabbitmq"
      restart: always